version: 2.1
orbs: {node: circleci/node@4.5.1, cypress: cypress-io/cypress@1.28.0, slack: circleci/slack@4.4.2, percy: percy/agent@0.1.3}
workflows:
  version: 2
  Scheduled-Smoke-Tests:
    jobs:
    - cypress/run:
        name: Scheduled Smoke Tests
        record: true
        store_artifacts: true
        command: npx cypress run --spec 'cypress/integration/E2E/*' --reporter mochawesome
        post-steps:
        - store_artifacts: {path: cypress/reports/mochareports}
        - run:
            name: Get artifacts
            when: on_fail
            command: |
              artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/JackMunn/LearnTesting/$CIRCLE_BUILD_NUM/artifacts" \
              -H "Accept: application/json" \
              -u "$CIRCLE_API_TOKEN:")
              echo "export ARTIFACT_RESPONSE=$artifacts" >> $BASH_ENV
        - slack/notify:
            channel: general
            event: fail
            custom: "{\n  \"blocks\": [\n    {\n      \"type\": \"section\",\n      \"text\": {\n        \"type\": \"mrkdwn\",\n        \"text\": \"This is a section block with an accessory image.\"\n      },\n      \"accessory\": {\n        \"type\": \"image\",\n        \"image_url\": \" $ARTIFACT_RESPONSE \",\n        \"alt_text\": \"cute cat\"\n      }\n    }\n  ]\n}     \n"
        - slack/notify: {channel: general, event: pass, template: basic_success_1, mentions: '@Jack Munn'}
