version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1.28.0
  slack: circleci/slack@4.4.2

# jobs:
#   notify:
#     executor:
#       name: node/default
#     steps:
#       - slack/notify:
#           channel: general
#           event: fail
#           template: basic_fail_1
#           mentions: '@JackMunn'
#       - slack/notify:
#           channel: general
#           event: pass
#           template: success_tagged_deploy_1
#           mentions: '@JackMunn'


workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run:
          name: Smoke tests only
          record: true
          store_artifacts: true  
          spec: cypress/integration/E2E/*
          post-steps:
            - slack/notify:
                channel: general
                event: fail
                template: basic_fail_1
                mentions: '@JackMunn'                      

          
      # - notify:
      #     context: slack-secrets
  thirty-min-workflow:
    triggers:
      - schedule:
          cron: "0 7,9,11,13,15,17,19 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          name: Whats the drivers first name?
          spec: cypress/integration/QuickQuoteQuestions/FirstName.test.js
          record: true
          store_artifacts: true              
      - cypress/run:
          name: Whats the drivers surname?
          spec: cypress/integration/QuickQuoteQuestions/SecondName.test.js
          record: true
          store_artifacts: true              
      - cypress/run:
          name: Whats the drivers email?
          spec: cypress/integration/QuickQuoteQuestions/Email.test.js
          record: true
          store_artifacts: true  
      - cypress/run:
          name: When do you want the subscription to start?
          spec: cypress/integration/QuickQuoteQuestions/SubscriptionStart.test.js
          record: true
          store_artifacts: true  
      - cypress/run:
          name: Please enter the drivers driving licence number 
          spec: cypress/integration/QuickQuoteQuestions/DLN.test.js
          record: true
          store_artifacts: true  
      - cypress/run:
          name: Please enter the drivers postcode
          spec: cypress/integration/QuickQuoteQuestions/DriversPostcode.test.js
          record: true
          store_artifacts: true  
 