version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1.28.0
  slack: circleci/slack@4.4.2
  percy: percy/agent@0.1.3
  

workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run:
          name: Smoke Tests
          record: true
          store_artifacts: true  
          spec: cypress/integration/E2E/*
          command-prefix: npx percy exec --
          post-steps:
            - store_test_results:
                path: test-results
            - slack/notify:
                channel: general
                event: fail
                template: basic_fail_1
                mentions: '@Jack Munn'
            - slack/notify:
                channel: general
                event: pass
                template: basic_success_1
                mentions: '@Jack Munn'   
      - percy/finalize_all:
            requires:
              - Smoke Tests


  Scheduled-Smoke-Tests:
    triggers:
      - schedule:
          cron: "0 7,8,9,11,13,15,17,19 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          name: Scheduled Smoke Tests
          record: true
          store_artifacts: true  
          spec: cypress/integration/E2E/*
          command-prefix: npx percy exec --
          post-steps:
            - store_test_results:
                path: test-results
            - slack/notify:
                channel: general
                event: fail
                template: basic_fail_1
                mentions: '@Jack Munn'
            - slack/notify:
                channel: general
                event: pass
                template: basic_success_1
                mentions: '@Jack Munn'  

  # Functional-Tests-11am-workflow:
  #   triggers:
  #     - schedule:
  #         cron: "0 11 * * 1,2,3,4,5"
  #         filters:
  #           branches:
  #             only:
  #               - main
  #   jobs:
  #     - cypress/run:
  #         name: Functional Tests in Quick Quote Questions
  #         spec: cypress/integration/QuickQuoteQuestions/*
  #         record: true
  #         store_artifacts: true    
  #         post-steps:
  #           - slack/notify:
  #               channel: general
  #               event: fail
  #               template: basic_fail_1
  #               mentions: '@Jack Munn'    
  #           - slack/notify:
  #               channel: general
  #               event: pass
  #               template: basic_success_1
  #               mentions: '@Jack Munn'                 

 