version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1.28.0
  slack: circleci/slack@4.4.2

jobs:
  notify:
    executor:
      name: node/default
    steps:
      - run: npx cypress run --record
      - slack/notify:
          channel: general
          event: fail
          template: basic_fail_1
          mentions: '@JackMunn'
      - slack/notify:
          channel: general
          event: pass
          template: success_tagged_deploy_1
          mentions: '@JackMunn'


workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run:
          record: true
          store_artifacts: true
      - notify:
          context: slack-secrets
  thirty-min-workflow:
    triggers:
      - schedule:
          cron: "0 7,9,11,13,15,17,19 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          record: true
          store_artifacts: true          
      - notify:
          context: slack-secrets




 