version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1.28.0
  slack: circleci/slack@4.4.2

# jobs:
#   notify:
#     executor:
#       name: node/default
#     steps:
#       - slack/notify:
#           channel: general
#           event: fail
#           template: basic_fail_1
#           mentions: '@Jack Munn'
#       - slack/notify:
#           channel: general
#           event: pass
#           template: success_tagged_deploy_1
#           mentions: '@Jack Munn'


workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run:
          name: Smoke Tests
          record: true
          store_artifacts: true  
          spec: cypress/integration/E2E/*
          post-steps:
            - store_test_results:
                path: test-results
            - slack/notify:
                channel: general
                event: fail
                template: basic_fail_1
                mentions: '@Jack Munn'
            - slack/notify:
                channel: general
                event: pass
                template: basic_success_1
                mentions: '@Jack Munn'                      

          
      # - notify:
      #     context: slack-secrets
  every-other-hour-workflow:
    triggers:
      - schedule:
          cron: "0 7,9,11,13,15,17,19 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/install: 
          name: Install dependencies
      - cypress/run:
          name: Smoke Tests
          requires:
            - Install dependencies
          record: true
          store_artifacts: true  
          spec: cypress/integration/E2E/*
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          post-steps:
            - store_test_results:
                path: test-results
            - slack/notify:
                channel: general
                event: fail
                template: basic_fail_1
                mentions: '@Jack Munn'
            - slack/notify:
                channel: general
                event: pass
                template: basic_success_1
                mentions: '@Jack Munn'  
      - cypress/run:
          name: Functional Tests in Quick Quote Questions
          spec: cypress/integration/QuickQuoteQuestions/*
          record: true
          store_artifacts: true    
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          post-steps:
            - slack/notify:
                channel: general
                event: fail
                template: basic_fail_1
                mentions: '@Jack Munn'          

 