version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:
  version: 2
  commit:
    jobs:
      - cypress/run
daytime hourly tests:
    triggers:
      - schedule:
          cron: '0 8,9,10,11,12,13,14,15,16 * * 1-5'
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run
      - store_test_results:
          path: test-results
      

 