version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.0



workflows:
  version: 2
  commit:
    jobs:
      - cypress/run
     

daytime every 30 mins tests:
    triggers:
      - schedule:
          cron: '0,30 8,9,10,11,12,13,14,15,16 * * 1-7'
          filters:
            branches:
              only:
                - main


 