version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.4.2

          
jobs:
  notify:
    executor:
      name: node/default
    docker:
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --record --key <record_key>
      - slack/notify:
          channel: general
          event: fail
          template: basic_fail_1
          mentions: '@JackMunn'
      - slack/notify:
          channel: general
          event: pass
          template: success_tagged_deploy_1
          mentions: '@JackMunn'


workflows:
  version: 2
  commit-workflow:
    jobs:
     # - cypress/run
      - notify:
          context: slack-secrets
  thirty-min-workflow:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
     # - cypress/run
      - notify:
          context: slack-secrets






 