version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.0

          
jobs:
  notify:
    executor:
      name: node/default
    steps:
      - slack/notify:
          channel: General
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run
      - notify:
          context: slack-secrets
  fifteen-min-workflow:
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run
      - notify






 