version: 2.1
orbs:
  node: circleci/node@4.5.1
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.0
  


workflows:
  version: 2
  commit-workflow:
    jobs:
      - cypress/run
  fifteen-min:
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run






 